-- MySQL Script generated by MySQL Workbench
-- Mon Aug 19 20:36:10 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student` (
  `student_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `groupe` VARCHAR(45) NULL,
  `sex` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`student_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`marks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`marks` (
  `marks_Id` INT NOT NULL AUTO_INCREMENT,
  `subject` VARCHAR(45) NULL,
  `mark` INT NULL,
  `student_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`marks_Id`),
  INDEX `studs mark_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `studs mark`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`student`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`student` (`student_id`, `name`, `groupe`, `sex`) VALUES (1, 'Петров', 'ИТ-11', 'м');
INSERT INTO `mydb`.`student` (`student_id`, `name`, `groupe`, `sex`) VALUES (2, 'Крылов', 'ИТ-12', 'м');
INSERT INTO `mydb`.`student` (`student_id`, `name`, `groupe`, `sex`) VALUES (3, 'Синицина', 'ВТ-21', 'ж');
INSERT INTO `mydb`.`student` (`student_id`, `name`, `groupe`, `sex`) VALUES (4, 'Карамазов', 'ВТ-22', 'м');
INSERT INTO `mydb`.`student` (`student_id`, `name`, `groupe`, `sex`) VALUES (5, 'Ромашкина', 'ПМ-31', 'ж');
INSERT INTO `mydb`.`student` (`student_id`, `name`, `groupe`, `sex`) VALUES (6, 'Козлов', 'ПМ-32', 'м');
INSERT INTO `mydb`.`student` (`student_id`, `name`, `groupe`, `sex`) VALUES (7, 'Кузнецов', 'ИТ-21', 'м');
INSERT INTO `mydb`.`student` (`student_id`, `name`, `groupe`, `sex`) VALUES (8, 'Жеребьева', 'ИМ-90', 'ж');
INSERT INTO `mydb`.`student` (`student_id`, `name`, `groupe`, `sex`) VALUES (9, 'Жуков', 'КФ-41', 'м');
INSERT INTO `mydb`.`student` (`student_id`, `name`, `groupe`, `sex`) VALUES (10, 'Теремин', 'ВТ-11', 'м');
INSERT INTO `mydb`.`student` (`student_id`, `name`, `groupe`, `sex`) VALUES (11, 'Васильев', 'КФ-31', 'м');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`marks`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`marks` (`marks_Id`, `subject`, `mark`, `student_id`) VALUES (1, 'Java', 4, 1);
INSERT INTO `mydb`.`marks` (`marks_Id`, `subject`, `mark`, `student_id`) VALUES (2, 'C#', 2, 1);
INSERT INTO `mydb`.`marks` (`marks_Id`, `subject`, `mark`, `student_id`) VALUES (3, 'Java', 3, 1);
INSERT INTO `mydb`.`marks` (`marks_Id`, `subject`, `mark`, `student_id`) VALUES (4, 'Java', 3, 2);
INSERT INTO `mydb`.`marks` (`marks_Id`, `subject`, `mark`, `student_id`) VALUES (5, 'C#', 4, 2);
INSERT INTO `mydb`.`marks` (`marks_Id`, `subject`, `mark`, `student_id`) VALUES (6, 'Java', 4, 2);
INSERT INTO `mydb`.`marks` (`marks_Id`, `subject`, `mark`, `student_id`) VALUES (7, 'Java', 4, 3);
INSERT INTO `mydb`.`marks` (`marks_Id`, `subject`, `mark`, `student_id`) VALUES (8, 'C#', 5, 3);
INSERT INTO `mydb`.`marks` (`marks_Id`, `subject`, `mark`, `student_id`) VALUES (9, 'Java', 5, 3);
INSERT INTO `mydb`.`marks` (`marks_Id`, `subject`, `mark`, `student_id`) VALUES (10, 'Java', 5, 4);
INSERT INTO `mydb`.`marks` (`marks_Id`, `subject`, `mark`, `student_id`) VALUES (11, 'C#', 2, 4);
INSERT INTO `mydb`.`marks` (`marks_Id`, `subject`, `mark`, `student_id`) VALUES (12, 'Java', 2, 4);
INSERT INTO `mydb`.`marks` (`marks_Id`, `subject`, `mark`, `student_id`) VALUES (13, 'Java', 2, 5);
INSERT INTO `mydb`.`marks` (`marks_Id`, `subject`, `mark`, `student_id`) VALUES (14, 'C#', 3, 5);
INSERT INTO `mydb`.`marks` (`marks_Id`, `subject`, `mark`, `student_id`) VALUES (15, 'C#', 4, 5);
INSERT INTO `mydb`.`marks` (`marks_Id`, `subject`, `mark`, `student_id`) VALUES (16, 'Java', 5, 6);
INSERT INTO `mydb`.`marks` (`marks_Id`, `subject`, `mark`, `student_id`) VALUES (17, 'C#', 4, 6);
INSERT INTO `mydb`.`marks` (`marks_Id`, `subject`, `mark`, `student_id`) VALUES (18, 'Java', 4, 7);
INSERT INTO `mydb`.`marks` (`marks_Id`, `subject`, `mark`, `student_id`) VALUES (19, 'C#', 5, 7);
INSERT INTO `mydb`.`marks` (`marks_Id`, `subject`, `mark`, `student_id`) VALUES (20, 'Java', 5, 8);
INSERT INTO `mydb`.`marks` (`marks_Id`, `subject`, `mark`, `student_id`) VALUES (21, 'C#', 4, 8);
INSERT INTO `mydb`.`marks` (`marks_Id`, `subject`, `mark`, `student_id`) VALUES (22, 'Java', 4, 9);
INSERT INTO `mydb`.`marks` (`marks_Id`, `subject`, `mark`, `student_id`) VALUES (23, 'C#', 4, 9);
INSERT INTO `mydb`.`marks` (`marks_Id`, `subject`, `mark`, `student_id`) VALUES (24, 'Java', 3, 10);
INSERT INTO `mydb`.`marks` (`marks_Id`, `subject`, `mark`, `student_id`) VALUES (25, 'C#', 5, 10);
INSERT INTO `mydb`.`marks` (`marks_Id`, `subject`, `mark`, `student_id`) VALUES (26, 'Java', 3, 11);
INSERT INTO `mydb`.`marks` (`marks_Id`, `subject`, `mark`, `student_id`) VALUES (27, 'C#', 2, 11);

COMMIT;

